# Generated by Django 2.1.1 on 2018-09-12 03:51

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0003_auto_20180911_1727'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Participant',
            new_name='Participation',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), null=True, size=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='videos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), null=True, size=10),
        ),
        migrations.AlterField(
            model_name='program',
            name='goal',
            field=models.TextField(verbose_name='Goal'),
        ),
        migrations.AlterField(
            model_name='program',
            name='requirement',
            field=models.TextField(blank=True, null=True, verbose_name='Requirement'),
        ),
    ]
