# Generated by Django 2.1.1 on 2018-09-12 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_auto_20180911_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='goal',
            field=models.TextField(verbose_name='Goal'),
        ),
        migrations.AlterField(
            model_name='program',
            name='requirement',
            field=models.TextField(blank=True, null=True, verbose_name='Requirement'),
        ),
        migrations.AlterField(
            model_name='userlesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lessons', to='academy.Lesson'),
        ),
    ]
