# Generated by Django 2.1.1 on 2018-09-12 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_auto_20180912_1051'),
        ('academy', '0004_auto_20180912_1114'),
    ]

    operations = [
    ]
