# Generated by Django 2.1.1 on 2018-09-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_merge_20180912_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
    ]
