# Generated by Django 2.1.1 on 2018-09-13 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_auto_20180913_1137'),
        ('academy', '0005_merge_20180912_1615'),
    ]

    operations = [
    ]
