# Generated by Django 2.1.1 on 2018-09-14 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_auto_20180913_1057'),
        ('academy', '0009_merge_20180913_1605'),
    ]

    operations = [
    ]
