# Generated by Django 2.1.1 on 2018-09-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0011_auto_20180914_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselesson',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courselesson',
            name='lesson',
        ),
        migrations.RenameField(
            model_name='userlesson',
            old_name='status',
            new_name='is_open',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lessons',
        ),
        migrations.AddField(
            model_name='userlesson',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CourseLesson',
        ),
    ]
